name: Update Portfolio Data

on:
  workflow_dispatch: {}

jobs:
  update-data:
    runs-on: ubuntu-latest
    steps:
      - name: debug-secret-check
        env:
          TWELVEDATA_API_KEY: ${{ secrets.TWELVEDATA_API_KEY }}
        run: echo "LENGTH=${#TWELVEDATA_API_KEY}"
